version: '1'

networks:
  skibidi:
    driver: bridge

services:
  db:
    container_name: skibidi-db
    image: winnkyaw/skibidi_db:latest
    networks:
      - skibidi
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skibidi_book
      MYSQL_USER: localhost
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
        
  frontend:
    container_name: skibidi-frontend
    image: winnkyaw/skibidi_book:latest
    networks:
      - skibidi
    ports:
      - "3000:3000"
    depends_on:
      - db
