version: '1'

networks:
  skibidi:
    driver: bridge

services:
  frontend:
    container_name: skibidi-frontend
    image: winnkyaw/skibidi_book:latest
    networks:
      - skibidi
    ports:
      - "3000:3000"

  db:
    container_name: skibidi-db
    image: mysql:5.7
    networks:
      - skibidi
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skibidi_book
      MYSQL_USER: localhost
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - Sql:/var/lib/mysql
    
